fix #3661: not logged in user: button to mark all as read leads to HTTP403 error
FreshRSS/FreshRSS pull request #3871
Opened 2021-10-09 19:20 UTC by math-GH

Closes #3661

Changes proposed in this pull request:
- if user is not logged in (=default/guest user) than no button to mark all articles as read. Show only a text

How to test the feature manually:
1. with default/guest user not logged in
2. scroll to the end of articles list
3. see: "There are no more articles" instead of "mark all as read" button
![grafik](https://user-images.githubusercontent.com/1645099/136671405-d08a3452-1632-4e1c-86de-5ffa6dfb25ff.png)

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

2021-10-09 20:05 UTC, Frenzie commented on app/views/helpers/pagination.phtml
> +	<?php } elseif ($url_mark_read) {
Seems you could just do this one-line change instead?
```suggestion
	<?php } elseif (FreshRSS_Auth::hasAccess() && $url_mark_read) { 
```

2021-10-10 11:32 UTC, math-GH commented on app/views/helpers/pagination.phtml
> +	<?php } elseif ($url_mark_read) {
I thought it too.
But: No, it does not work properly.
Because of the `else`

2021-10-10 11:41 UTC, Frenzie commented on app/views/helpers/pagination.phtml
> +	<?php } elseif ($url_mark_read) {
How do you mean because of the else? My entire point is that it looks like you're unnecessarily duplicating the else.

2021-10-10 18:07 UTC, math-GH commented on app/views/helpers/pagination.phtml
> +	<?php } elseif ($url_mark_read) {
now I see your point.

Thanks!

2021-10-10 18:10 UTC, math-GH commented on app/views/helpers/pagination.phtml
> +	<?php } elseif ($url_mark_read) {
fixed it with the commit

2021-10-10 19:04 UTC, Frenzie approved these changes

2021-10-14 11:34 UTC, Alkarex commented on app/views/helpers/pagination.phtml
> +		<div id="bigMarkAsRead" href=".">
`<div href` is probably an error?

2021-10-14 11:34 UTC, Alkarex requested changes
Cf. comment

2021-10-14 15:45 UTC, math-GH commented on app/views/helpers/pagination.phtml
> +		<div id="bigMarkAsRead" href=".">
I would delete the `href`, because it is not a real link for the user

2021-10-16 10:19 UTC, merged