Add pwa
FreshRSS/FreshRSS pull request #3890
Opened 2021-10-15 12:38 UTC by proletarius101

Closes https://github.com/FreshRSS/FreshRSS/issues/2033 https://github.com/FreshRSS/FreshRSS/issues/1963

Changes proposed in this pull request:

- Add a pwa manifest as defined in https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs
-
-

How to test the feature manually:

1. Open FreshRSS in a mobile browser
2. Tap the `Install` button in the browser
3. An icon appears in the home screen which can open a standalone FreshRSS app

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

2021-10-15 13:35 UTC, Frenzie approved these changes
lgtm

2021-10-15 13:39 UTC, proletarius101 commented
Maybe wait a sec. I'm implementing a service worker

2021-10-15 13:42 UTC, Frenzie commented
A second? While I admit I haven't actively investigated (because we already have the likes of EasyRSS at our disposal) I always assumed that'd be a project that'd eat up at least several nights. :rofl:

2021-10-15 13:43 UTC, proletarius101 commented
Well, you may merge it now. Service worker is more complicated than I think.

2021-10-15 13:43 UTC, Frenzie commented on p/themes/manifest.json
> +      "sizes": "16x16 64x64"
It's also 32x32 and 48x48, isn't it?

2021-10-15 13:48 UTC, Frenzie commented
We'll have to wait for @Alkarex. As per the repo settings I can only merge PRs once the CI runs successfully (which given that I or at least someone still has to port it over to GitHub Actions is currently never, hint hint if you happen to know GHA and have a half hour you'd like to spend on that :angel:).

2021-10-16 11:06 UTC, Frenzie requested changes
(withdrawing approval to prevent confusion)

2021-10-16 11:06 UTC, Frenzie commented on p/themes/manifest.json
> +  "start_url": "/i/",
```suggestion
  "start_url": "..",
```

2021-10-16 11:11 UTC, Alkarex commented on app/layout/layout.phtml
> +		<link rel="manifest" href="<?= Minz_Url::display('/themes/manifest.json') ?>">
```suggestion
		<link rel="manifest" href="<?= Minz_Url::display('/themes/manifest.json') ?>" />
```

2021-10-16 11:11 UTC, Alkarex commented on p/themes/manifest.json
> +}
```suggestion
}

```

2021-10-16 12:50 UTC, proletarius101 commented on p/themes/manifest.json
> +      "sizes": "16x16 64x64"
fixed

2021-10-16 12:53 UTC, proletarius101 commented on p/themes/manifest.json
> +  "start_url": "/i/",
fixed

2021-10-17 10:32 UTC, Frenzie commented on p/themes/manifest.json
> -  "orientation": "any",
Is leaving this out equivalent to any? Enforcing portrait would strike me as undesirable.

2021-10-17 10:33 UTC, Frenzie approved these changes
lgtm

2021-10-17 10:34 UTC, proletarius101 commented on p/themes/manifest.json
> -  "orientation": "any",
As most apps, the orientation is controlled by the system rather than the app

2021-10-17 10:35 UTC, Frenzie commented on p/themes/manifest.json
> -  "orientation": "any",
It's mainly that I don't know what prompted you to include it in the first place. I assumed there was a reason for it. ;-)

2021-10-23 22:18 UTC, Alkarex commented
> We'll have to wait for @Alkarex. As per the repo settings I can only merge PRs once the CI runs successfully (which given that I or at least someone still has to port it over to GitHub Actions is currently never, hint hint if you happen to know GHA and have a half hour you'd like to spend on that 👼).

CI fixed https://github.com/FreshRSS/FreshRSS/pull/3920

2021-10-23 22:29 UTC, Alkarex commented
I will have to look at bit more about it. I am not (yet) convinced of the advantages. This PR is probably fine as it does not "cost" much, but the related https://github.com/FreshRSS/FreshRSS/pull/3896 is much larger, with dependencies, and for an unclear advantage. Additional input welcome.

2021-10-23 22:46 UTC, proletarius101 commented
> I will have to look at bit more about it. I am not (yet) convinced of the advantages. This PR is probably fine as it does not "cost" much, but the related #3896 is much larger, with dependencies, and for an unclear advantage. Additional input welcome.

This PR doesn't rely on https://github.com/FreshRSS/FreshRSS/pull/3896. Vise versa. So they can be merged independently.

- This PR is to enable [Installability](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Introduction#installability), making it native to the system
- The service worker is for [Network independence](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Introduction#network_independence), which makes reading pre-cached articles offline possible.
  - It also provides transition between poor connectivity and good connectivity

2021-10-24 09:17 UTC, Frenzie commented
A potential advantage of a PWA (not in the current poc unless I missed some more recent changes) would be that syncing read/unread status and the like could be handled by the service worker, without having interrupted or absent connections throwing spanners in the works.

2021-10-24 15:28 UTC, merged

2021-10-24 15:35 UTC, Alkarex commented
Ok, let's give this one a try. Yes @Frenzie , regarding the second PR, having a way to work partially offline would be interesting to look into, but that should probably require reworking the UI rendering to be more client side, potentially taking advantage of our API like an app. But the question is then whether a full app is not better for this role and there are a few good clients already.

2021-10-24 17:54 UTC, Frenzie commented
Right, I never looked into it myself because we already have EasyRSS and many others. But you can also build up to something progressively. I'm ambivalent towards it. :-) https://gomakethings.com/service-worker-strategies/

2021-11-01 22:19 UTC, mathContao commented
I love this PWA feature. Tested it with Mozilla Firefox on Android.

2026-09-03 18:38 UTC, dminca commented
tested 1.29.1 on Vanadium (Android) and it's not working as expected, it's just saved as a bookmark on the home.

2026-09-03 19:17 UTC, Frenzie commented
It's not that very different from a bookmark anyway, but I see the two separate options.
<img width="1080" height="732" alt="IMG_20260903_211558" src="https://github.com/user-attachments/assets/ee6f33ef-41b4-4684-b7ad-d728202de344" />

2026-09-03 19:43 UTC, dminca commented
This is the difference

<img width="1080" height="854" alt="IMG_20260903_214258" src="https://github.com/user-attachments/assets/f5d11661-e841-4207-a7ab-a5a017c426b2" />
<img width="1080" height="1078" alt="IMG_20260903_214102" src="https://github.com/user-attachments/assets/dbee6a2a-883c-46d8-a10f-09e44ccc3dc9" />

It seems FreshRSS is not available as a PWA

2026-09-03 19:53 UTC, Frenzie commented
It works in Chrome and Vivaldi. You'd have to try a few other browsers to see if it's something about that specific installation or something in combination with Vanadium. I assume you mean you have seen the option to "install" in Vanadium before?

2026-09-03 21:09 UTC, dminca commented
I just downloaded Vivaldi on Android from the Play Store.

Only have the option to _add page to > Home screen_ and this mimics the same behaviour, still no PWA 🤔 (as seen in Fig. 2 I shared above)

> I assume you mean you have seen the option to "install" in Vanadium before?

yes, it's Fig. 1 from the screenshots I shared above.

2026-09-03 21:26 UTC, Frenzie commented
It's probably best to open an issue. I'm out of ideas for the moment. Maybe it's some kind of reverse proxy issue?

2026-09-03 21:30 UTC, dminca commented
No worries, will do that. Thanks a lot so far :)