enhancement subscription management page
FreshRSS/FreshRSS pull request #3893
Opened 2021-10-15 22:54 UTC by math-GH

Closes #3257

Before:
![grafik](https://user-images.githubusercontent.com/1645099/137562293-f69adced-723e-4334-9b5b-27888405ddf5.png)

![grafik](https://user-images.githubusercontent.com/1645099/137562367-2bbf66f3-2fe2-44b2-9684-a15bc991dc68.png)

![grafik](https://user-images.githubusercontent.com/1645099/137562404-052525f7-461f-47b6-afd1-9eae8ad7da9b.png)

After:
![grafik](https://user-images.githubusercontent.com/1645099/137562200-b6432814-a47a-4aa9-b9b1-0dca5fa55795.png)

![grafik](https://user-images.githubusercontent.com/1645099/137562209-49a1bf23-e5de-49d4-a405-098013be7743.png)

![grafik](https://user-images.githubusercontent.com/1645099/137562214-245ca7c7-911f-4ec3-9dd0-3e39d034903f.png)

Changes proposed in this pull request:
see screenshots
(the button "show only feeds with errors" appears only, when there are errors)

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

2021-10-16 07:36 UTC, Frenzie approved these changes
lgtm, something about the alignment of that button at the top looks potentially a bit weird?

2021-10-16 07:36 UTC, Frenzie commented on app/views/helpers/category/update.phtml
> +					<?php endif;?>
```suggestion
				<?php endif;?>
```

2021-10-16 10:08 UTC, mathContao commented
> 
> 
> lgtm, something about the alignment of that button at the top looks potentially a bit weird?

fixed

![grafik](https://user-images.githubusercontent.com/1645099/137583498-b417546f-7e62-4324-880f-36e07926a8ff.png)

2021-10-16 10:27 UTC, Frenzie commented
That .box style is only used on that specific page?

2021-10-16 10:31 UTC, mathContao commented
> 
> 
> That .box style is only used on that specific page?

also in user queries pages (new layout still on the edge branch)
![grafik](https://user-images.githubusercontent.com/1645099/137583995-86f39bf3-6538-4e87-a45d-805cc4893df9.png)

2021-10-16 10:34 UTC, Frenzie commented
> also in user queries pages (new layout still on the edge branch)

In any case, as long as you've made sure it looks good everywhere it's used. ^_^

2021-10-19 09:23 UTC, Alkarex requested changes

2021-10-19 09:23 UTC, Alkarex commented on app/i18n/en/sub.php
> -		'moved_category_deleted' => 'When you delete a category, its feeds are automatically classified under <em>%s</em>.',
I believe you are still using this translation string, aren't you?

2021-10-19 09:51 UTC, math-GH commented on app/i18n/en/sub.php
> -		'moved_category_deleted' => 'When you delete a category, its feeds are automatically classified under <em>%s</em>.',
This text is still used. It moved from the "Subscription overview page" to the "category settings slider"

see:
https://user-images.githubusercontent.com/1645099/137562214-245ca7c7-911f-4ec3-9dd0-3e39d034903f.png

2021-10-19 10:21 UTC, Alkarex commented on app/i18n/en/sub.php
> -		'moved_category_deleted' => 'When you delete a category, its feeds are automatically classified under <em>%s</em>.',
Indeed, my point is that it looks like this PR removes this text, which therefore creates an error.

2021-10-19 11:01 UTC, math-GH commented on app/i18n/en/sub.php
> -		'moved_category_deleted' => 'When you delete a category, its feeds are automatically classified under <em>%s</em>.',
ok. you are right.
I do not know why I deleted it.
Fixed it.

2021-10-19 13:08 UTC, Alkarex approved these changes

2021-10-19 13:08 UTC, merged