close panel with esc shortcut
FreshRSS/FreshRSS pull request #3901
Opened 2021-10-18 19:49 UTC by math-GH

Closes #3450

Changes proposed in this pull request:
- `ESC` closes the panel
- little beauty: on larger screens there is more background to close the panel with the mouse

How to test the feature manually:
1. go to global view
2. click on category name
3. article list will be opened in a overflow
4. press `ESC` to close the overflow

Pull request checklist:
- [x] clear commit messages
- [x] code manually tested

2021-10-18 20:31 UTC, Frenzie requested changes

2021-10-18 20:31 UTC, Frenzie commented on p/scripts/global_view.js
> +	document.body.onkeydown = function (ev) {
`document.addEventListener('keydown', …`

2021-10-18 20:31 UTC, Frenzie commented on p/scripts/global_view.js
> +		document.querySelector('#overlay .close').click();
I assume this should be inside the `(k === 'ESC')`? Every keypress will close the popup.

2021-10-18 20:32 UTC, math-GH commented on p/scripts/global_view.js
> +		document.querySelector('#overlay .close').click();
🙈

2021-10-18 20:48 UTC, Frenzie commented on p/scripts/global_view.js
> +	document.body.onkeydown = function (ev) {
See https://github.com/FreshRSS/FreshRSS/pull/3902/files for full example.

2021-10-19 10:00 UTC, math-GH commented on p/scripts/global_view.js
> +		document.querySelector('#overlay .close').click();
fixed

2021-10-19 11:38 UTC, math-GH commented on p/scripts/global_view.js
> +	document.body.onkeydown = function (ev) {
fixed

2021-10-19 12:26 UTC, Frenzie commented on p/scripts/global_view.js
> +	document.body.onkeydown = function (ev) {
I think you may have forgotten to push?

2021-10-19 14:25 UTC, math-GH commented on p/scripts/global_view.js
> +	document.body.onkeydown = function (ev) {
now the fix is available

2021-10-19 14:27 UTC, Frenzie commented on p/scripts/global_view.js
> +	}
```suggestion
	});
```
Also there's something weird about the indentation.

2021-10-19 14:36 UTC, Frenzie commented on p/scripts/global_view.js
> +		}
Could you explain why you're doing this?

2021-10-19 14:38 UTC, Frenzie commented on p/scripts/global_view.js
> +		if (k === 'ESC') {
That is, as opposed to:
```suggestion
		if (k === 'ESC' || k === 'ESCAPE') {
```
(assuming that any of that stuff is necessary *at all* given that IE11 is deprecated and it's probably for IE8 or something)

2021-10-19 14:39 UTC, math-GH commented on p/scripts/global_view.js
> +		}
I reuse the click event of the dark overlay around the panel. When the user clicks with the mouse on it, than the panel will be closed.

2021-10-19 14:42 UTC, Frenzie commented on p/scripts/global_view.js
> +		}
Yes, but
```
	if (k === 'ESC') {
			k = 'ESCAPE';
		}
		if (k == 'ESCAPE') {
```
Gives me the heebie jeebies. ;-)

2021-10-21 09:30 UTC, Alkarex commented on p/scripts/global_view.js
> +		let k = (ev.key.trim() || ev.code).toUpperCase();
```suggestion
		const k = (ev.key.trim() || ev.code).toUpperCase();
```

2021-10-21 09:33 UTC, merged