Add xdebug for devs
FreshRSS/FreshRSS pull request #5594
Opened 2023-08-16 12:14 UTC by ColonelMoutarde

Changes proposed in this pull request:

- add xdebug in project only for developpeurs

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested

2023-08-16 20:39 UTC, Alkarex commented on .devcontainer/Dockerfile
> +FROM alpine:3.18 as dev
Still a single-stage build, right? So no need to have a name

2023-08-16 20:44 UTC, Alkarex commented on .devcontainer/Dockerfile
> +    && docker-php-ext-enable xdebug \
That does not build

2023-08-16 20:54 UTC, Alkarex requested changes
Does not work for multiple reasons. See comments

2023-08-16 20:55 UTC, Alkarex commented on tests/app/Services/ImportServiceTest.php
That does not seem to be related to this PR, is it? And fails the tests

2023-08-17 07:58 UTC, ColonelMoutarde commented on tests/app/Services/ImportServiceTest.php
Indeed, I don't understand what's going on.

2023-08-25 17:12 UTC, closed without merging