Add Japanese to font-family
FreshRSS/FreshRSS pull request #5671
Opened 2023-09-25 08:00 UTC by superuser7777

Please consider changing the CSS as shown below.
This modification improves display readability for Japanese people.

Add
`"Osaka",`

Change before
`font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", "PingFang SC", "Microsoft YaHei", sans-serif;`

After change
`font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", "Osaka", "PingFang SC", "Microsoft YaHei", sans-serif;`

The Chinese fonts such as "PingFang SC" and "Microsoft YaHei" can be displayed like Japanese, but the kanji are greatly broken down, making them difficult for Japanese people to read.

--
Thank you for the great software!
I've migrated all my RSS readers to FreshRSS!

2023-09-25 08:11 UTC, Frenzie approved these changes

2023-09-25 08:34 UTC, Alkarex commented
We should probably update all the themes, which have overriden the base font definition, e.g.:

2023-09-25 08:36 UTC, Alkarex commented
Related to https://github.com/FreshRSS/FreshRSS/pull/1541

@hoilc if you are around, do you have any comment? For instance a negative consequence, we might have overlooked?

2023-09-25 08:44 UTC, Alkarex commented
I am wondering whether adding (only) "Osaka" is the most appropriate fix. It seems to be only for Apple. Isn't e.g. "MS Gothic" more common?

2023-09-25 08:47 UTC, Alkarex commented
Note for later: we should add a way to tweak font parameters independently of the default settings proposed by the themes (we might have an issue somewhere already)

2023-10-03 16:07 UTC, math-GH requested changes
It is very nice to know that FreshRSS is used in Japan too :)

Please support us here with screenshots "before" and "after" the change.

Please find another default font families that is installed on Windows by default. Linux would be fine too.

2023-10-15 22:04 UTC, math-GH commented
the conflicted files can be deleted to solve the conflict

2023-11-21 16:54 UTC, Alkarex commented
@superuser7777 Your feedback would be welcome in https://github.com/FreshRSS/FreshRSS/pull/5895 , for instance related to font selection and calendar selection (which calendar system do you use?)

2026-07-08 20:34 UTC, Alkarex commented
Tests welcome:
* https://github.com/FreshRSS/FreshRSS/pull/9002

2026-07-09 19:02 UTC, closed without merging