Remove new window target in normal view
FreshRSS/FreshRSS pull request #6934
Opened 2024-10-22 20:35 UTC by tydavis

As of v1.24.3, clicking the title of an article in normal view opens a
new tab in the browser. Remove the link reference to expand the article
within the reader, while still allowing for direct external view via
the "See on original website" link at the end of the row.

2024-10-22 21:43 UTC, Alkarex commented
> As of v1.24.3, clicking the title of an article in normal view opens a new tab in the browser

That is not the expected behaviour. This could be a sign of a FreshRSS extension, which is misbehaving. Please try again after disabling your FreshRSS extensions.

2024-10-23 01:22 UTC, tydavis commented
@Alkarex This is present without extensions (vanilla install). The `target="_blank"` anchor is present in the code currently: https://github.com/FreshRSS/FreshRSS/blob/edge/app/views/helpers/index/normal/entry_header.phtml#L59

My guess is that this was duplicated from the "See on website" anchor on L90.

2024-10-23 09:17 UTC, Alkarex commented
The `<a target="_blank"` is meant for systems without JavaScript and looks correct. I cannot reproduce the problem you are facing.
Can you provide some details about your Web browser and FreshRSS setup? Any JavaScript error in the console? Could you try with another browser without any Web browser extension? Would you be able to post a screen recording here to make sure we talk about the same thing?

2024-10-23 17:33 UTC, tydavis commented
Looks like my "Stop The Madness" plugin (Safari, also Firefox & Chrome) is forcing HTML5 behavior to be honored -- per https://html.spec.whatwg.org/#navigable-target-names  `target="_blank"` always opens a new window. 

Why does the list entry need to contain a link when, without it, the application performs exactly as expected?

Attached are shots of the demo site and my edited local site.
<img width="685" alt="Screenshot 2024-10-23 at 10 30 43" src="https://github.com/user-attachments/assets/2f559371-1ef2-4096-a320-11da9807b962">
<img width="893" alt="Screenshot 2024-10-23 at 10 29 20" src="https://github.com/user-attachments/assets/e2d779d9-e653-4bae-8291-d89cebe4e55b">

2024-10-23 19:58 UTC, Alkarex commented
> Why does the list entry need to contain a link when, without it, the application performs exactly as expected?

Because our Web UI also works to a good extent without JavaScript at all, and the non-JavaScript behaviour is to open links in a new tab. I will try something else in another PR

2024-10-23 20:13 UTC, Alkarex commented
Could you try https://github.com/FreshRSS/FreshRSS/pull/6937 ?

2024-10-24 20:43 UTC, math-GH requested changes

2024-10-24 20:43 UTC, math-GH commented on app/views/helpers/index/normal/entry_header.phtml
> +		<?= $this->entry->title() ?><?php
simply: no way.
The CSS classes are needed

2024-10-24 20:49 UTC, math-GH commented
> > Why does the list entry need to contain a link when, without it, the application performs exactly as expected?
> 
> Because our Web UI also works to a good extent without JavaScript at all, and the non-JavaScript behaviour is to open links in a new tab. I will try something else in another PR

I am thinking about a better non-JS solution: Instead of having an external link the title here could have a #anchor that makes the following article visible (via CSS `:target`). It would make the `target:"_blank"` cruft

2024-10-24 20:50 UTC, closed without merging

2024-10-24 22:56 UTC, tydavis commented
@Alkarex - #6937 reproduced the "new tab" behavior. I'm curious about the anchor with CSS target option

2024-10-24 23:31 UTC, tydavis commented
>Edit: The reason for this <a> is the middle mouse click, that opens the link in a new tab
Do we hide the "see on original website" link for mobile / smaller screens?

2024-10-24 23:35 UTC, tydavis commented
I turned off my extension for the domain and behavior returned to what you described. For reference, https://underpassapp.com/StopTheMadness/

2024-10-24 23:36 UTC, tydavis commented
Sorry for raising an issue / PR.

2024-10-26 10:15 UTC, math-GH commented
> > Edit: The reason for this  is the middle mouse click, that opens the link in a new tab
Do we hide the "see on original website" link for mobile / smaller screens?

not by default. I wished you can tweak it with the CSS extension. If needed I can help